import React, { useCallback, useState, useEffect } from "react";
import { useDropzone } from "react-dropzone";
import pngImage from "../../../assets/images/pngIcon.png";

import SendIcon from '@mui/icons-material/Send';
import SaveIcon from '@mui/icons-material/Save';
import { Button } from "@mui/material";
import LoadingButton from '@mui/lab/LoadingButton';
import UpLoadButton from "./UpLoadButton";

const Dropbox = () => {

    const [isValid, setIsValid] = useState<boolean>(false);
    const [uploadedImage, setUploadedImage] = useState<string | null>(null);
    const onDrop = useCallback(async (acceptedFiles: File[]) => {
        if (acceptedFiles.length > 0) {
            const file = acceptedFiles[0];
            const fileUrl = URL.createObjectURL(file);
            setUploadedImage(fileUrl);
            console.log("Đã chọn file:", file);
        }
    }, []);
    const { getRootProps, getInputProps } = useDropzone({
        accept: {
            'image/png': ['.png'],
        },
        onDrop,
        multiple: false
    });

    return (
        <div className=" p-xl-2 border-3  bg-white mt-5 d-flex flex-column align-items-center p-3" style={{ height: "70vh" }}  >
            <h1 className=" text-black">Detect Image Generated By Ai</h1>
            {uploadedImage ? (
                <>
                    <div className="row h-100 w-100" >
                        <div className="dropbox col-md-8 d-flex align-items-center justify-content-center p-3  " style={{ border: "2px dashed black", cursor: "pointer" }} {...getRootProps()}>
                            <input {...getInputProps()} />
                            <img src={uploadedImage} alt="Uploaded" className="img-fluid" style={{ maxHeight: "70%", maxWidth: "70%" }} />
                        </div>
                        <div className="col-md-4 d-flex flex-column px-5">
                            <Button variant="contained" endIcon={<SendIcon />}>
                                Detect Image
                            </Button>
                            <LoadingButton
                                loading
                                loadingPosition="start"
                                startIcon={<SaveIcon />}
                                variant="outlined"
                            >
                                Save
                            </LoadingButton>
                        </div>
                    </div>

                </>
            ) : (
                <>
                    <div className="dropbox container d-flex flex-column align-items-center justify-content-center w-100 h-100" style={{ border: "2px dashed black", cursor: "pointer" }} {...getRootProps()}>
                        <input {...getInputProps()} />
                        <img src={pngImage} alt="Default" className="img-fluid" style={{ height: "10vh" }} />
                        <h4 className="mt-3">Drag and drop an image file (JPG, PNG, BMP, and more)</h4>
                        <UpLoadButton className="mt-5 w-25 bg" />
                    </div>
                </>

            )}

        </div >
    );
};

export default Dropbox;
